/**
 * 与 content script 的协议消息类型
 */
export const MSG = {
  PING: 'BHT_PING',
  GET_PAGE_INFO: 'BHT_GET_PAGE_INFO',
  SCAN_JOBS: 'BHT_SCAN_JOBS',
  OPEN_JOB: 'BHT_OPEN_JOB',
  START_CHAT: 'BHT_START_CHAT',
  GET_CHAT_SELF_MESSAGES: 'BHT_GET_CHAT_SELF_MESSAGES',
  SEND_TEXT: 'BHT_SEND_TEXT',
  SEND_IMAGE: 'BHT_SEND_IMAGE',
  SEND_FILE_META: 'BHT_SEND_FILE_META',
  HIGHLIGHT_JOBS: 'BHT_HIGHLIGHT_JOBS',
  DIAGNOSE: 'BHT_DIAGNOSE',
  TASK_EVENT: 'BHT_TASK_EVENT',
  LOG_EVENT: 'BHT_LOG_EVENT',
  GET_STATE: 'BHT_GET_STATE',
  SAVE_SETTINGS: 'BHT_SAVE_SETTINGS',
  SAVE_FILTERS: 'BHT_SAVE_FILTERS',
  SAVE_TEMPLATE: 'BHT_SAVE_TEMPLATE',
  SAVE_LISTS: 'BHT_SAVE_LISTS',
  SAVE_RESUMES: 'BHT_SAVE_RESUMES',
  SAVE_BINDINGS: 'BHT_SAVE_BINDINGS',
  RUN_PREVIEW: 'BHT_RUN_PREVIEW',
  CONFIRM_AND_START: 'BHT_CONFIRM_AND_START',
  PAUSE_TASK: 'BHT_PAUSE_TASK',
  RESUME_TASK: 'BHT_RESUME_TASK',
  STOP_TASK: 'BHT_STOP_TASK',
  SKIP_CURRENT: 'BHT_SKIP_CURRENT',
  EXPORT_CONFIG: 'BHT_EXPORT_CONFIG',
  IMPORT_CONFIG: 'BHT_IMPORT_CONFIG',
  CLEAR_LOGS: 'BHT_CLEAR_LOGS',
  GET_LOGS: 'BHT_GET_LOGS'
};

export async function sendToTab(tabId, type, payload = {}) {
  return chrome.tabs.sendMessage(tabId, { type, payload });
}

export async function sendRuntime(type, payload = {}) {
  return chrome.runtime.sendMessage({ type, payload });
}
